/**
 * WHAT A FRAME COSTS THIS TAB — the composition, driven end to end through the
 * framework's own `deltas` hook.
 *
 * IT IS A LEG, NOT A FILE (`just bench`), and it exists because nothing in this
 * tree measured this any more. The framework benches the MERGE
 * (`@kolu/surface`'s `src/solid/collectionDeltas.bench.ts`) and
 * `@olai/format`'s `patch.bench.ts` benches the PATCH; between them sits what a
 * browser actually pays for one edited file — the frame, the fold, and the two
 * walks over the key list that ride beside it — and that was PR #263's second
 * standing deferral, carried in `./outlines.ts`'s own text. This closes it.
 * Deliberately not part of `just check`: a timing that fails a lane on a busy
 * machine teaches nobody anything.
 *
 * THE FRAMES REALLY GO THROUGH THE FRAMEWORK. Every arm below owns a
 * `useCollectionDeltas` over a hand-pushed stream — the same shape kolu's own
 * bench uses — so the store write, the fold dispatch and the batch a frame is
 * applied inside are the real ones, and what is read afterwards is
 * `createOutlines`, the function `App.tsx` calls. The bench this replaces
 * SIMULATED the store write by calling the framework's merge directly, which is
 * how it came to report a number that could not move when the framework
 * changed underneath it; nothing here is re-spelled.
 *
 * ## The frame: three arms, cumulative
 *
 *   - `frame` — the hook and nothing reading it: what the framework does with a
 *     frame. The control, so the two below can be read as "and then this much
 *     on top" rather than as one number nobody can attribute — and it carries
 *     the fixed cost of pushing a frame and waiting for it to land, which every
 *     arm pays and none of them chose.
 *   - `view` — plus the fold: `derived()` observed, so the patcher runs on the
 *     frame that invalidated it.
 *   - `tab` — plus `files()`, `faces()` and `broken()`: the whole composition,
 *     which is the thing this leg is named for. The gap between it and `view`
 *     is what the two per-frame walks over the key list cost, which
 *     `./outlines.ts` names in its own text and could not price.
 *
 * ## The reconnect: what a link flap costs the next search
 *
 * The other half, and the other deferral (#263's first). A wire snapshot
 * re-initialises the fold — one honest full rebuild per reconnect, which the
 * design ruled — but WHICH OBJECTS that rebuild is made of is a choice, and it
 * decides whether every per-record cache in the app survives the flap:
 *
 *   - `wire` — seeded with the entries the frame carries, freshly decoded. This
 *     is `outlines.ts` as it stood before this branch, re-inlined here for the
 *     reason `patch.bench.ts` keeps the id-map clone it replaced: a before that
 *     the harness cannot print is a before nobody can check.
 *   - `held` — seeded from the STORE, which value-diffed the snapshot and kept
 *     the objects it already had. This is `createOutlines` as it now is.
 *
 * Both are then asked one search question, and the question is the point:
 * `@olai/format`'s matcher keeps its folded text in a `WeakMap` on the RECORD,
 * so an arm holding the records it held before the flap answers warm and an arm
 * holding fresh ones folds the corpus again. A FRESH SNAPSHOT PER ROUND, so the
 * cold arm is cold every round rather than warmed by its own first answer.
 *
 * RUN IT WITH `just bench`, which is `bun --conditions browser`. Without that
 * condition Bun resolves SolidJS's server build, where a memo is computed once
 * and never invalidated — every arm would then measure an empty loop and report
 * a magnificent number. The guards below are what make that a failure rather
 * than a result.
 */

import { collection } from "@kolu/surface"
import type { CollectionDeltasMsg } from "@kolu/surface/define"
import { useCollectionDeltas } from "@kolu/surface/solid"
import { derive, type Derived, faceOf, matching, parseFilter, patch } from "@olai/format"
import {
  median,
  outlineOf,
  retitled,
  retitledIn,
  timed,
  timesSaid,
  vaultOf,
} from "@olai/format/testlib"
import { LOADED, type Manifest, OutlineEntry } from "@olai/surface"
import { Effect, Queue, Schema, Stream } from "effect"
import { createEffect, createRoot } from "solid-js"

import { createOutlines, type OutlineEntries, type Outlines } from "./outlines.ts"

const FILES = Number(process.env["OLAI_BENCH_FILES"] ?? 1000)
const RECORDS = Number(process.env["OLAI_BENCH_RECORDS"] ?? 21)
const EDITS = Number(process.env["OLAI_BENCH_EDITS"] ?? 40)
/** How many reconnects each arm of the second section is asked to survive. */
const FLAPS = 5

/** The corpus, GENERATED BY `@olai/format/testlib` rather than here: the same
 *  vault `packages/format/src/patch.bench.ts` and `complete/tags.bench.ts` run
 *  on, so what a frame costs a tab, what the patch inside it costs, and what a
 *  completion asks of the view it leaves are numbers about one directory. */
const corpus = vaultOf({ files: FILES, records: RECORDS })
const paths = [...corpus.keys()]
const records = [...corpus.values()].reduce((total, text) => total + text.split("\n").length, 0)

// ── the wire, hand-driven ──────────────────────────────────────────────

type Frame = CollectionDeltasMsg<string, OutlineEntry>

/** The collection descriptor the hook is handed. `useCollectionDeltas` never
 *  reads it — it is what types the keys and the values — so this is the wire's
 *  own declaration (`@olai/surface`'s `outlines`) restated as the smallest
 *  thing that types it, rather than a second surface to keep in step. */
const outlines = collection({
  name: "outlines",
  keySchema: Schema.String,
  schema: OutlineEntry,
})

/**
 * A stream somebody pushes frames into — Effect's own queue, read as a stream.
 *
 * `@kolu/surface` has one of these (`controllableStream`) and it is a testlib
 * the package does not export, so this is the same idea reached through the
 * dependency both of them already stand on rather than hand-rolled a second
 * time: an unbounded queue is the buffering, and `Stream.fromQueue` is the
 * reading. What a bench needs of it is the half that pushes; it never ends,
 * because an arm that has stopped receiving is not a shape anything below
 * measures.
 */
const controllable = (): { source: Stream.Stream<Frame>; push: Push } => {
  const queue = Effect.runSync(Queue.unbounded<Frame>())
  return {
    source: Stream.fromQueue(queue),
    push: (frame) => void Effect.runSync(Queue.offer(queue, frame)),
  }
}

/** Let a pushed frame cross the stream's fiber and land: `setImmediate` runs
 *  after the microtask queue, which is where a frame's whole journey — the
 *  fiber, the store write, the folds, and the effects that observe them —
 *  happens. It is inside every timed window below, and the `frame` arm is what
 *  says what it costs. */
const settled = (): Promise<void> => new Promise((resolve) => setImmediate(resolve))

/** One file's entry, as the server publishes one: the records, the face the
 *  server built when the bytes changed, and the revision the set was at. */
const entryOf = (file: string, text: string, rev: number): OutlineEntry => {
  const outline = outlineOf(text, file)
  return { rev, nodes: outline.nodes, broken: null, face: faceOf(outline) }
}

/** The whole set, decoded afresh — the wire's first frame, and every reconnect
 *  snapshot. Called again per flap on purpose: a reconnect re-serializes the
 *  same content into NEW objects, and that is the thing the second section is
 *  about. */
const snapshotOf = (rev = 1): Frame => ({
  kind: "snapshot",
  entries: paths.map((file) => [file, entryOf(file, corpus.get(file) as string, rev)]),
})

/** Which file edit `which` rewrites — asked by the edit and by the guard that
 *  reads the answer back, so the two cannot come to mean different files. */
const fileFor = (which: number): string => paths[which % paths.length] as string

/** One edit: one record's title rewritten in one file, as that file's whole
 *  entry at the next revision — exactly the frame a probe tick sends for one
 *  edited outline. */
const editOf = (which: number): Frame => {
  const file = fileFor(which)
  const text = retitled(corpus.get(file) as string, which)
  return { kind: "delta", upserts: [[file, entryOf(file, text, which + 2)]], removes: [] }
}

/** The manifest, as a directory that has loaded. A constant: this leg is about
 *  the collection, and a cell that moved would be a second thing changing. */
const loaded = (): Manifest => LOADED

// ── the frame: three arms ──────────────────────────────────────────────

/** Deliver one frame to one arm. */
type Push = (frame: Frame) => void

interface Arm {
  readonly push: Push
  /** Which edit this arm's OWN answer says it is at, read off the file the
   *  edit named. Off the clock, and the whole guard against an arm that
   *  stopped recomputing. */
  readonly said: (file: string) => number | undefined
}

/** One arm: the framework's hook over a stream this bench pushes into, and
 *  whatever `read` builds on top of it — the three lines every arm in both
 *  sections opens with, spelled once. The reactive root is never disposed
 *  because the process ends with the leg. */
const driven = <T>(read: (entries: OutlineEntries) => T): { push: Push; it: T } =>
  createRoot(() => {
    const { source, push } = controllable()
    return { push, it: read(useCollectionDeltas(outlines, { source })) }
  })

/** One arm of the first section: the hook, and whatever `observe` decides to
 *  read from it every frame. The effect inside `observe` is what makes a
 *  frame's work happen when the frame LANDS rather than when a reader gets
 *  round to asking — which is what a rendered page does and what a lazy memo
 *  would not. */
const arm = (
  observe: (entries: OutlineEntries) => (file: string) => number | undefined,
): Arm => {
  const { push, it } = driven(observe)
  return { push, said: it }
}

/** THE FRAMEWORK ALONE: the frame written into the store, and nothing derived
 *  from it. Its answer is read straight out of the store, which is what says
 *  the frame landed at all. */
const frameOnly = (): Arm =>
  arm((entries) => (file) => retitledIn(entries.byKey(file)?.()?.nodes ?? []))

/** An arm over the SHIPPED composition, reading whatever `observe` reads of it
 *  every frame. The two below differ in exactly that and in nothing else, which
 *  is what makes the gap between them attributable to what the second one
 *  reads. */
const composed = (observe: (view: Outlines) => void): Arm =>
  arm((entries) => {
    const view = createOutlines(entries, loaded)
    createEffect(() => observe(view))
    return (file) => retitledIn(view.derived()?.byFile.get(file) ?? [])
  })

/** THE FOLD: `derived` observed and nothing else. */
const viewOnly = (): Arm => composed((view) => void view.derived())

/** THE WHOLE COMPOSITION: everything `App.tsx` reads off this module. */
const wholeTab = (): Arm =>
  composed((view) => {
    view.derived()
    view.files()
    view.faces()
    view.broken()
  })

/** One frame, pushed and waited for, in milliseconds — `@olai/format/testlib`'s
 *  `timed` for a window that has to be AWAITED, which the testlib's own is not.
 *  Same clock (`Bun.nanoseconds`), so the two numbers this leg prints per arm
 *  and every number the other three legs print are one clock's.
 *
 *  THE FRAME IS THE MEASUREMENT: the work an effect does happens when the write
 *  that invalidated it finishes, so the whole of "a file changed and this tab
 *  has a view of it again" is inside this window. */
const frameCost = async (push: Push, frame: Frame): Promise<number> => {
  const at = Bun.nanoseconds()
  push(frame)
  await settled()
  return (Bun.nanoseconds() - at) / 1e6
}

/**
 * The three arms, alternated round by round and timed per frame.
 *
 * ALTERNATED because two arms run one after the other are two arms of a machine
 * in two moods, and going last in a round is worth more than some of the
 * differences this leg is asked to see (`@olai/format/testlib`'s `alternating`
 * makes the same argument for the synchronous legs; this one is async, so the
 * rotation is written out here).
 */
const theFrame = async (): Promise<void> => {
  const arms = [
    ["frame", frameOnly()] as const,
    ["view", viewOnly()] as const,
    ["tab", wholeTab()] as const,
  ]
  const first = new Map<string, number>()
  for (const [name, end] of arms) {
    first.set(name, await frameCost(end.push, snapshotOf()))
    const said = end.said(fileFor(0))
    if (said !== undefined) {
      throw new Error(`${name} says it is at edit ${said} before any edit was made`)
    }
  }
  const times = new Map(arms.map(([name]) => [name, [] as Array<number>]))
  for (let which = 0; which < EDITS; which++) {
    const frame = editOf(which)
    // The SAME frame object reaches all three, and the rotation is what stops
    // one of them always going first.
    const order = arms.map((_, at) => arms[(at + which) % arms.length] as (typeof arms)[number])
    for (const [name, end] of order) {
      ;(times.get(name) as Array<number>).push(await frameCost(end.push, frame))
      const said = end.said(fileFor(which))
      if (said !== which) {
        throw new Error(
          `${name} is at edit ${said ?? "none"} after edit ${which}` +
            ` — the arm answered a frame it never recomputed`,
        )
      }
    }
  }
  console.log(`\nONE FILE EDITED, over ${EDITS} frames — what the tab pays for it`)
  for (const [name] of arms) {
    console.log(
      `  ${timesSaid(name, times.get(name) as Array<number>, 6)}` +
        `   (first frame ${(first.get(name) as number).toFixed(2)}ms)`,
    )
  }
}

// ── the reconnect: what a link flap costs the next search ──────────────

/**
 * Somebody typing one word into the box.
 *
 * A SELECTIVE one, and that is a decision rather than a convenience: the
 * matcher folds every record of the corpus whatever the query says, but it also
 * BUILDS a row per hit, and a word answering half the vault buries the fold
 * under the assembly of its own answer. What a flap costs is the DIFFERENCE
 * between the two arms — the corpus folded a second time — so the query is
 * chosen to leave that difference in plain sight; a broader search costs both
 * arms the same extra rows on top of it, and the gap between them is the same
 * gap. `#topic7` is one of the tags `vaultOf` writes into its titles.
 */
const TYPED = "#topic7"
/** The day the relative words would count from. A constant: nothing here asks
 *  for one, and a clock in a benchmark measures a different question in
 *  January. */
const TODAY = "2026-08-13"

const searched = (view: Derived): number => matching(view, parseFilter(TYPED, TODAY)).length

/** An arm of the second section: a hook of its own, and a view seeded one of
 *  the two ways. */
interface Flapped {
  readonly push: Push
  readonly view: () => Derived
}

const flapArm = (seeded: (entries: OutlineEntries) => () => Derived | undefined): Flapped => {
  const { push, it: read } = driven((entries) => {
    const view = seeded(entries)
    createEffect(() => view())
    return view
  })
  return {
    push,
    view: () => {
      const held = read()
      if (held === undefined) throw new Error("the arm has no view — no snapshot ever landed")
      return held
    },
  }
}

/** WHAT `outlines.ts` DID: the fold seeded with the entries the frame carries.
 *  Re-inlined here because it is the "before" of this comparison and lives
 *  nowhere else any more. */
const seededFromTheWire = (entries: OutlineEntries): (() => Derived | undefined) =>
  entries.fold({
    init: (all) => patch(derive([]), { upserts: all, removes: [] }),
    step: patch,
  })

/** WHAT IT DOES: the shipped composition, whose fold reads its seed out of the
 *  store the snapshot was just applied to. */
const seededFromTheStore = (entries: OutlineEntries): (() => Derived | undefined) => {
  const view = createOutlines(entries, loaded)
  return () => view.derived()
}

const theReconnect = async (): Promise<void> => {
  const arms = [
    ["wire", flapArm(seededFromTheWire)] as const,
    ["held", flapArm(seededFromTheStore)] as const,
  ]
  // ONE SNAPSHOT for both, so both start out holding the same record objects —
  // and one search each, so both start WARM. What the flap does to that warmth
  // is the whole measurement.
  const first = snapshotOf()
  for (const [, end] of arms) end.push(first)
  await settled()
  const hits = new Set(arms.map(([, end]) => searched(end.view())))
  if (hits.size !== 1 || (hits.values().next().value ?? 0) === 0) {
    throw new Error(
      `the two arms answer different searches (${[...hits].join(", ")})` +
        " — there is nothing to compare",
    )
  }

  const times = new Map(arms.map(([name]) => [name, [] as Array<number>]))
  const rebuilds = new Map(arms.map(([name]) => [name, [] as Array<number>]))
  for (let flap = 0; flap < FLAPS; flap++) {
    // A RECONNECT: the same content, re-serialized into fresh objects, which is
    // what the retry fence turns a transport drop into. Fresh per flap so the
    // cold arm cannot be warmed by its own previous answer.
    const again = snapshotOf()
    const order = arms.map((_, at) => arms[(at + flap) % arms.length] as (typeof arms)[number])
    for (const [name, end] of order) {
      const rebuilt = await frameCost(end.push, again)
      // The search itself is synchronous, so it is timed with the testlib's own
      // clock — the one every other `just bench` leg reports from.
      let answered = 0
      const cost = timed(() => {
        answered = searched(end.view())
      })
      if (answered !== hits.values().next().value) {
        throw new Error(`${name} answered ${answered} hits after the flap, not ${
          hits.values().next().value
        } — the arm is not measuring what it says`)
      }
      ;(rebuilds.get(name) as Array<number>).push(rebuilt)
      ;(times.get(name) as Array<number>).push(cost)
    }
  }
  console.log(`\nA LINK FLAP, over ${FLAPS} reconnects — the snapshot, then one search`)
  for (const [name] of arms) {
    console.log(
      `  ${name.padEnd(6)} snapshot ${
        median(rebuilds.get(name) as Array<number>).toFixed(2)
      }ms   then one search ${median(times.get(name) as Array<number>).toFixed(2)}ms`,
    )
  }
}

console.log(
  `vault: ${corpus.size} files, ${records} records\n` +
    `runtime: ${
      process.versions.bun !== undefined ? `bun ${process.versions.bun}` : `node ${process.version}`
    }`,
)
await theFrame()
await theReconnect()
