import { expect, test } from "bun:test"
import { createInspectorState } from "./state.ts"

test("inspector history survives presentation replacement but ends with its activation", () => {
  const state = createInspectorState()
  state.door.setOpen(true)
  state.nowRead("extension", "first")
  state.setGroupOpen("Pages", true)
  state.disclose("extension", true)
  // A door closing or moving is presentation, not a new authorization reading.
  state.door.setOpen(false)
  state.door.setOpen(true)
  expect(state.read().get("extension")).toBe("first")
  expect(state.opened()["Pages"]).toBe(true)
  expect(state.disclosed()["extension"]).toBe(true)
  state.close()
  expect(state.door.open()).toBe(false)
  expect(state.read().size).toBe(0)
  expect(state.opened()["Pages"]).toBeUndefined()
  expect(state.disclosed()["extension"]).toBeUndefined()
  expect(() => state.nowRead("extension", "unseen")).toThrow("closed")
  expect(() => state.setGroupOpen("Pages", true)).toThrow("closed")
  const next = createInspectorState()
  expect(next.read().size).toBe(0)
  expect(next.door.open()).toBe(false)
  expect(next.opened()["Pages"]).toBeUndefined()
  next.nowRead("extension", "second")
  expect(next.read().get("extension")).toBe("second")
  expect(state.read().size).toBe(0)
  next.close()
})

test("optional links withdraw and reconnect independently of the panel", () => {
  const state = createInspectorState()
  const first = () => null
  const second = () => null
  state.door.setOpen(true)
  const release = state.link(first)
  expect(state.file()).toBe(first)
  release()
  expect(state.file()).toBeUndefined()
  expect(state.door.open()).toBe(true)
  const releaseSecond = state.link(second)
  release()
  expect(state.file()).toBe(second)
  state.close()
  releaseSecond()
  expect(state.file()).toBeUndefined()
  expect(() => state.link(first)).toThrow("closed")
})

test("a configuration request opens its row and cannot outlive the inspector", () => {
  const state = createInspectorState()
  state.reveal("example")
  expect(state.door.open()).toBe(true)
  expect(state.disclosed().example).toBe(true)
  expect(state.requested()).toBe("example")
  state.reveal("replacement")
  state.revealed("example")
  expect(state.requested()).toBe("replacement")
  state.revealed("replacement")
  expect(state.requested()).toBeUndefined()
  expect(state.disclosed().replacement).toBe(true)
  state.close()
  expect(() => state.reveal("example")).toThrow("closed")
})
