/** Stable DOM identifiers owned by this renderer. Shared consumers import
 * this static contract; no provider state or activation is loaded with it. */
export const TESTID = {
  outlineTree: "outline-tree",
  node: "node",
  nodeTitle: "node-title",
  landingSaid: "landing-said",
  date: "date",
  datePicker: "date-picker",
  datePickerDay: "date-picker-day",
  datePickerSet: "date-picker-set",
  datePickerCancel: "date-picker-cancel",
  datePickerNotice: "date-picker-notice",
  datePickerSaid: "date-picker-said",
  repeat: "repeat",
  repeatPicker: "repeat-picker",
  repeatPickerRule: "repeat-picker-rule",
  repeatPickerSet: "repeat-picker-set",
  repeatPickerCancel: "repeat-picker-cancel",
  repeatPickerNotice: "repeat-picker-notice",
  repeatPickerSaid: "repeat-picker-said",
  propFold: "prop-fold",
  propKey: "prop-key",
  propEdit: "prop-edit",
  propEditKey: "prop-edit-key",
  propAdd: "prop-add",
  propSaid: "prop-said",
  hotFact: "hot-fact",
  foldedDone: "folded-done",
  took: "took",
  desc: "desc",
  descHit: "desc-hit",
  noteMark: "note-mark",
  toggle: "toggle",
  nodeMenu: "node-menu",
  nodeMenuPanel: "node-menu-panel",
  nodeMenuItem: "node-menu-item",
  nodeMenuConfirm: "node-menu-confirm",
  nodeMenuSaid: "node-menu-said",
  blocked: "blocked",
  seeRefs: "see-refs",
  afterRefs: "after-refs",
  refDrop: "ref-drop",
  backlinks: "backlinks",
  backlinksSummary: "backlinks-summary",
  backlinkSeeRefs: "backlink-see-refs",
  backlinkMentionRefs: "backlink-mention-refs",
  edgeVerb: "edge-verb",
  edgePanel: "edge-panel",
  edgeHeld: "edge-held",
  edgeDrop: "edge-drop",
  edgeSearch: "edge-search",
  edgeHit: "edge-hit",
  edgeHitPlace: "edge-hit-place",
  edgeHitProp: "edge-hit-prop",
  edgeSearchFailed: "edge-search-failed",
  edgeSaid: "edge-said",
  edgePanelClose: "edge-panel-close",
  movePicker: "move-picker",
  moveSearch: "move-search",
  moveHit: "move-hit",
  moveHitPlace: "move-hit-place",
  moveHitProp: "move-hit-prop",
  moveRefused: "move-refused",
  moveSearchFailed: "move-search-failed",
  moveSaid: "move-said",
  movePickerClose: "move-picker-close",
  nodeRef: "node-ref",
  nodeGutter: "node-gutter",
  zoom: "zoom",
  checkbox: "checkbox",
  titleEditor: "title-editor",
  descEditor: "desc-editor",
  newRow: "new-row",
  completions: "completions",
  completionItem: "completion-item",
  completionItemPlace: "completion-item-place",
  completionItemProp: "completion-item-prop",
  completionsError: "completions-error",
  editRefusal: "edit-refusal",
  editNudge: "edit-nudge",
  startLine: "start-line",
  dragHandle: "drag-handle",
  dropLine: "drop-line",
  dropRefused: "drop-refused",
  dropRefusedSaid: "drop-refused-said",
  sweepBand: "sweep-band",
  selectionBar: "selection-bar",
  selectionCount: "selection-count",
  selectionTrash: "selection-trash",
  selectionConfirm: "selection-confirm",
  selectionCancel: "selection-cancel",
  selectionNote: "selection-note",
  selectionSaid: "selection-said",
  emptyUnder: "empty-under",
  zoomTitle: "zoom-title",
  breadcrumbs: "breadcrumbs",
  crumb: "crumb",
  notFound: "not-found",
  filterBar: "filter-bar",
  filterInput: "filter-input",
  doneFlip: "done-flip",
  doneRelease: "done-release",
  filterCount: "filter-count",
  filterClear: "filter-clear",
  filterRefusal: "filter-refusal",
  filterFailure: "filter-failure",
} as const

export type TestId = (typeof TESTID)[keyof typeof TESTID]

import type {} from "@olai/ui-primitives/testids.ts"
type OwnedTestIds = typeof TESTID
declare module "@olai/ui-primitives/testids.ts" {
  interface TestIdTables { readonly "plugins/outlines": OwnedTestIds }
}
